version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'r00tp@ssw0rd123'
      MYSQL_DATABASE: joms
      MYSQL_USER: joms
      MYSQL_PASSWORD: '3ntityp@ssw0rd123'
    ports:
      - 3307:3306
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - fake-nft-cats-network
  fake-nft-cats:
    container_name: fake-nft-cats
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${EXPOSED_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - fake-nft-cats-network

volumes:
  mysql-db:

networks:
  fake-nft-cats-network:
